config/routes.rb
Rails.application.routes.draw do
  get 'search/results' => 'search#results'
  get root :to => 'pages#home'
  get '/about' => 'pages#about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
  delete '/login' => 'sessions#destroy'
  post '/' => 'search#search'
  get '/results' => 'pages#results'

  get '/recipe/:id' => 'pages#recipe'
  get '/recipe/:id/delete' => 'pages#recipe_destroy'
  
  get '/signup' => 'pages#render_sign_up'
  post 'signup' => 'pages#sign_up'
  get '/signup/failure' => 'pages#signup_failure'
  get '/signup/success' => 'pages#signup_success'
  
  get '/create/' => 'pages#createrecipe'
  post '/create_recipe' => 'pages#create_recipe'
  get '/create/ingredients' => 'pages#create_recipe_ingredients'
  post '/create/ingredients' => 'pages#create_recipe_ingredients'
  get '/create/instructions' => 'pages#recipe_instructions'
  post'/create/instructions' => 'pages#create_instructions'
  get '/create/success' => 'pages#recipe_success'
  get '/create/failure' => 'pages#recipe_failure' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :ingredients
  has_many :instructions
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if session[:pantry].nil? 
      session[:pantry] = {}
    end
    @logged_in_user = User.find_by :id => session[:user_id]
  end
  
  def results
    
    # place to store recipes found based on ingredients possessed
    @retrieved = []
    
    # put results here from recipe function
    @results = []
    
    # create recipe objects for easy rendering in results view
    def recipe (recipe_id, name)
      if recipe_id
       this_recipe = Recipe.find(recipe_id.to_i)
      else
       this_recipe = Recipe.find_by(name)
      end

      creation = {
          :name => this_recipe[:name],
          :instructions => this_recipe.instructions.all,
          :ingredients => this_recipe.ingredients.all
      }
      # return the object
      creation
    end


    if session[:pantry].nil?
      puts "Redirected to index because session[:pantry] is nil."
      redirect_to '/'
    else
      p "pantry:"
      p session[:pantry]  
      # For each ingredient in the pantry, find all recipes
      session[:pantry].each do |id, name|
        this_ingredient = Ingredient.find_by(name: name)
        these_recipes = this_ingredient.recipes.all
        these_recipes.each do |item|
          @retrieved.push(item)
        end

      end

    end
  end

  # create a recipe
  def create_recipe
    @logged_in_user = User.find_by :id => session[:user_id]
    @userid = @logged_in_user[:id].to_i

      # Create the recipes
      @this_recipe = Recipe.create(
        :title => params[:title],
        :user_id => @logged_in_user[:id].to_i
      )
      
      @counter = 0
      # Create the instructions for the recipe
      params[:instruction].each do |item|
        @counter += 1
        this_instruction = Instruction.create!(
          :content => item,
          :step_number => @counter,
          :recipe_id => @this_recipe[:id]
        )

        @this_recipe.instructions << this_instruction
      end


      # Create the ingredients for the recipe
      params[:ingredient].each do |item|
        this_ingredient = Ingredient.find_or_create_by(
          :name => item
        )

        @this_recipe.ingredients << this_ingredient
      end
      flash[:user_create] = "Recipe created!"
      # redirect_to '/'
  end

  def render_sign_up
  end

  def sign_up
    @user = User.create(
      :username => params[:username],
      :first_name => params[:firstName],
      :last_name => params[:lastName],
      :email => params[:email],
      :password_digest => BCrypt::Password.create(params[:password])
    )
    flash[:user_created] = @user[:first_name]
  redirect_to '/'
  end

  def recipe
    @recipe = Recipe.find_by(id: params[:id].to_i)
  end

  def recipe_destroy
    recipe = Recipe.find(params[:id].to_i)
    recipe.destroy
    redirect_to '/'
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    result = Ingredient.find_by(name: params[:ingredient_name])
    if result
      @pantry = result
      session[:pantry][result[:id]] = result[:name]
    else
      flash[:error] = "No result found!"
    end
  redirect_to '/'
  end

  def results

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @error_message = flash[:error]
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id # store their id in user's session hash
      redirect_to root_path
    else
      flash[:error] = 'Invalid Credentials'
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%;">
  <head>
    <title>Recipedb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="height: 100%;">
    <%= yield %>
    <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/createrecipe.html.erb
<div class="container">

  <h1> Create a recipe </h1>
  <%= form_with(url: "/create_recipe", method: 'post') do %>
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" class="form-control" id="title" aria-describedby="firstName">
        <div class="ingredients">
          <label for="title">Ingredients</label>
          <input type="text" name="ingredient[]" class="form-control" id="ingredient[]" aria-describedby="ingredient">
        </div>
        <button id ="more-ingredients" class="btn btn-success">More ingredients</button>
        <div class="instructions">
          <label for="title">Instructions</label>
          <input type="text" name="instruction[]" class="form-control" id="instruction[]" aria-describedby="firstName">
        </div>
        <button id ="more-instructions" class="btn btn-success">More instructions</button>      
      </div>
    <%= submit_tag("Submit") %>

  <% end %>


</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {
  ingredient = `<input type="text" name="ingredient[]" class="form-control" id="ingredient[]" aria-describedby="ingredient">`;

  instruction = `<input type="text" name="instruction[]" class="form-control" id="instruction[]" aria-describedby="firstName">`;


  $('#more-ingredients').on('click', function(e) {
    $('.ingredients').append(ingredient);
    e.preventDefault();
  });

  $('#more-instructions').on('click', function() {
    $('.instructions').append(ingredient);
  });
})
</script>
 

app/views/pages/home.html.erb
<div class="notice"><%= flash[:user_created] %></div>

<div class="splash container-fluid d-flex h-75">
  <header class="row">
    <h1 class="col-3">RecipeDB</h1>
    <div class="auth col-3">
      <% if @logged_in_user.nil? %>
        <%= button_to("Login", controller: "sessions", action: "new") %>
        <form class = "btn btn-success" action="/signup">
          <button>Sign Up</button>
        </form>
      <% else %>
        <h4> Welcome back, <%= @logged_in_user.first_name %></h4>
        <%= button_to("Logout", login_path, :method => :delete) %>
      <% end %>
      <%= button_to("Create a recipe", { action: "createrecipe"}, {:method => :get, :form_class => "btn btn-success"}) %>
    </div>
  </header>
  
  <div class="search-bar row">
    <%= form_with(url: "/", method: "post") do %>
      <%= text_field_tag(:ingredient_name) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>
<form class = "btn btn-success" action="/results">
  <button>Results</button>
</form>

<div>
  <% if session[:pantry] %>
    <ul>
      <% session[:pantry].each do |id, name| %>
        <li><%= name %></li>
       <% end %>
    </ul>
  <% end %>
</div>

app/views/pages/recipe.html.erb
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-to
  " alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">
      <ol>
      <% @recipe.instructions.all.each do |item| %>
        
        <li><%= item %></li>
      <% end %>
      <ol>
    </p>
    <a href="/recipe/<%= @recipe[:id]/delete %>" class="btn btn-danger">Delete</a>
  </div>
</div>

app/views/pages/render_sign_up.html.erb
<div class="container">

    <h1> Sign Up </h1>
    <%= form_with(url: "/signup", method: 'post') do %>

      <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" name="firstName" class="form-control" id="firstName" aria-describedby="firstName" placeholder="Jane">
      </div>

      <div class="form-group">
        <label for="lastName">Last Name</label>
        <input type="text" name="lastName" class="form-control" id="lastName" aria-describedby="lastName" placeholder="Smith">
      </div>

      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" class="form-control" id="username" aria-describedby="username" placeholder="Enter username">
      </div>
      <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control" id="password" placeholder="Enter password">
      </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
  <% end %>
</div>

app/views/pages/results.html.erb
<h1>Results</h1>


<div class="container-fluid card-holder">
  <% @retrieved.each do |item| %>
    <div class="card" style="width: 18rem;">
      <img src="http://placekitten.com/300/200" class="card-img-top" alt="Food pic">
      <div class="card-body">
        <h3><%= item[:title] %></h3>
        <h5 class="card-title">Ingredients</h5>
        <p class="card-text">
          <ul>
            <% item.ingredients.all.each do |ingredient| %>
              <li><%= ingredient[:name] %></li>
            <% end %>
          </ul>
        </p>
        <h5 class="card-title">Instructions</h5>
        <p class="card-text">
          <ol>
            <% item.instructions.all.each do |instruction| %>
              <li><%= instruction[:content] %></li>
            <% end %>
          </ol>
        </p>
      </div>
    </div>
  <% end %>  
</div>

app/views/pages/sign_up.html.erb
<div class="container">

    <h1> Sign Up </h1>
    <%= form_with(url: "/signup", method: 'post') do %>

      <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" name="firstName" class="form-control" id="firstName" aria-describedby="firstName" placeholder="Jane">
      </div>

      <div class="form-group">
        <label for="lastName">Last Name</label>
        <input type="text" name="lastName" class="form-control" id="lastName" aria-describedby="lastName" placeholder="Smith">
      </div>

      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" class="form-control" id="username" aria-describedby="username" placeholder="Enter username">
      </div>
      <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control" id="password" placeholder="Enter password">
      </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Success!</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-success" action="/">Go back</button>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/search/results.html.erb
<h1>Let's Eat!</h1>

app/views/search/search.html.erb
<h1>Search#search</h1>
<p>Find me in app/views/search/search.html.erb</p>